name: Create Badge Action

on:
  pull_request:
    types: [closed, labeled]

jobs: 
  action:
    runs-on: ubuntu-latest
    steps:
      - name: Actions
        uses: actions/checkout@v2

      - name: Badgr Create Badge
        if: ${{ github.event.pull_request.merged == true }}
        uses: yajushiSri/Badgr-Create-Badge@v1.0.0
        id: badge
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          repo: ${{github.repository}}
          sha: ${{github.sha}}
          username: ${{secrets.BADGR_USERNAME}}
          password: ${{secrets.BADGR_PASSWORD}}